url: "https://www.mistersourcerer.com"
baseurl: "" # the subpath of your site, e.g. /blog
title: "Mister Sourcerer's Bloggy Blog [msbb]"
plugins:
  - jekyll-feed
lang: "en-us"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Ricardo Valeriano"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# jekyll-feed:
feed:
  categories:
    - en-us
    - pt-br
